// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: git.go
//
// Generated by this command:
//
//	mockgen -source=git.go -destination=git_test/git_mocks.go -package=git_test --copyright_file=../../../.license-preamble
//

// Package git_test is a generated GoMock package.
package git_test

import (
	context "context"
	reflect "reflect"
	time "time"

	git "github.com/microsoft/azure-linux-dev-tools/internal/utils/git"
	gomock "go.uber.org/mock/gomock"
)

// MockGitProvider is a mock of GitProvider interface.
type MockGitProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGitProviderMockRecorder
	isgomock struct{}
}

// MockGitProviderMockRecorder is the mock recorder for MockGitProvider.
type MockGitProviderMockRecorder struct {
	mock *MockGitProvider
}

// NewMockGitProvider creates a new mock instance.
func NewMockGitProvider(ctrl *gomock.Controller) *MockGitProvider {
	mock := &MockGitProvider{ctrl: ctrl}
	mock.recorder = &MockGitProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitProvider) EXPECT() *MockGitProviderMockRecorder {
	return m.recorder
}

// Checkout mocks base method.
func (m *MockGitProvider) Checkout(ctx context.Context, repoDir, commitHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", ctx, repoDir, commitHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Checkout indicates an expected call of Checkout.
func (mr *MockGitProviderMockRecorder) Checkout(ctx, repoDir, commitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockGitProvider)(nil).Checkout), ctx, repoDir, commitHash)
}

// Clone mocks base method.
func (m *MockGitProvider) Clone(ctx context.Context, repoURL, destDir string, options ...git.GitOptions) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, repoURL, destDir}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Clone", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockGitProviderMockRecorder) Clone(ctx, repoURL, destDir any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, repoURL, destDir}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockGitProvider)(nil).Clone), varargs...)
}

// GetCommitHashBeforeDate mocks base method.
func (m *MockGitProvider) GetCommitHashBeforeDate(ctx context.Context, repoDir string, dateTime time.Time) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitHashBeforeDate", ctx, repoDir, dateTime)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitHashBeforeDate indicates an expected call of GetCommitHashBeforeDate.
func (mr *MockGitProviderMockRecorder) GetCommitHashBeforeDate(ctx, repoDir, dateTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitHashBeforeDate", reflect.TypeOf((*MockGitProvider)(nil).GetCommitHashBeforeDate), ctx, repoDir, dateTime)
}

// GetCurrentCommit mocks base method.
func (m *MockGitProvider) GetCurrentCommit(ctx context.Context, repoDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentCommit", ctx, repoDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentCommit indicates an expected call of GetCurrentCommit.
func (mr *MockGitProviderMockRecorder) GetCurrentCommit(ctx, repoDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentCommit", reflect.TypeOf((*MockGitProvider)(nil).GetCurrentCommit), ctx, repoDir)
}
