// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: component.go
//
// Generated by this command:
//
//	mockgen -source=component.go -destination=components_testutils/component_mocks.go -package=components_testutils --copyright_file=../../../../../.license-preamble
//

// Package components_testutils is a generated GoMock package.
package components_testutils

import (
	reflect "reflect"

	components "github.com/microsoft/azure-linux-dev-tools/internal/app/azldev/core/components"
	specs "github.com/microsoft/azure-linux-dev-tools/internal/app/azldev/core/specs"
	projectconfig "github.com/microsoft/azure-linux-dev-tools/internal/projectconfig"
	gomock "go.uber.org/mock/gomock"
)

// MockComponent is a mock of Component interface.
type MockComponent struct {
	ctrl     *gomock.Controller
	recorder *MockComponentMockRecorder
	isgomock struct{}
}

// MockComponentMockRecorder is the mock recorder for MockComponent.
type MockComponentMockRecorder struct {
	mock *MockComponent
}

// NewMockComponent creates a new mock instance.
func NewMockComponent(ctrl *gomock.Controller) *MockComponent {
	mock := &MockComponent{ctrl: ctrl}
	mock.recorder = &MockComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponent) EXPECT() *MockComponentMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockComponent) GetConfig() *projectconfig.ComponentConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(*projectconfig.ComponentConfig)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockComponentMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockComponent)(nil).GetConfig))
}

// GetDetails mocks base method.
func (m *MockComponent) GetDetails() (*components.ComponentDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetails")
	ret0, _ := ret[0].(*components.ComponentDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetails indicates an expected call of GetDetails.
func (mr *MockComponentMockRecorder) GetDetails() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetails", reflect.TypeOf((*MockComponent)(nil).GetDetails))
}

// GetName mocks base method.
func (m *MockComponent) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockComponentMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockComponent)(nil).GetName))
}

// GetSpec mocks base method.
func (m *MockComponent) GetSpec() specs.ComponentSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpec")
	ret0, _ := ret[0].(specs.ComponentSpec)
	return ret0
}

// GetSpec indicates an expected call of GetSpec.
func (mr *MockComponentMockRecorder) GetSpec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpec", reflect.TypeOf((*MockComponent)(nil).GetSpec))
}
