// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package upstreamcommit_test

import (
	"path/filepath"
	"testing"

	"github.com/microsoft/azure-linux-dev-tools/internal/global/testctx"
	"github.com/microsoft/azure-linux-dev-tools/internal/projectconfig"
	"github.com/microsoft/azure-linux-dev-tools/internal/upstreamcommit"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/fileperms"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/fileutils"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const testStoreDir = "/project/base/upstream-commits"

func TestStoreSaveAndGet(t *testing.T) {
	ctx := testctx.NewCtx()
	store := upstreamcommit.NewStore(ctx.FS(), testStoreDir)

	require.NoError(t, store.Save("bash", "abcdef1234567"))

	data, err := fileutils.ReadFile(ctx.FS(), filepath.Join(testStoreDir, "bash.toml"))
	require.NoError(t, err)
	assert.Equal(t, `# This file was generated by 'azldev component refresh-upstream-commit'
# Do not edit this file, changes will be lost
# For more details see 'azldev component refresh-upstream-commit --help'
[components]
[components.bash]
[components.bash.spec]
upstream-commit = 'abcdef1234567'
`, string(data))

	commit, exists, err := store.Get("bash")
	require.NoError(t, err)
	assert.True(t, exists)
	assert.Equal(t, "abcdef1234567", commit)

	require.NoError(t, store.Save("bash", "1234567abcdef"))
	commit, exists, err = store.Get("bash")
	require.NoError(t, err)
	assert.True(t, exists)
	assert.Equal(t, "1234567abcdef", commit)
}

func TestStoreSaveReplacesExistingGeneratedContent(t *testing.T) {
	ctx := testctx.NewCtx()
	store := upstreamcommit.NewStore(ctx.FS(), testStoreDir)
	path := filepath.Join(testStoreDir, "bash.toml")

	require.NoError(t, fileutils.MkdirAll(ctx.FS(), testStoreDir))
	require.NoError(t, fileutils.WriteFile(ctx.FS(), path, []byte(`
[components.bash.spec]
type = "local"
path = "bash.spec"
upstream-commit = "oldcommit"

[components.bash.build]
defines = { stale = "value" }
`), fileperms.PublicFile))

	require.NoError(t, store.Save("bash", "abcdef1234567"))

	data, err := fileutils.ReadFile(ctx.FS(), path)
	require.NoError(t, err)
	assert.NotContains(t, string(data), "type")
	assert.NotContains(t, string(data), "path")
	assert.NotContains(t, string(data), "defines")
	assert.Contains(t, string(data), "upstream-commit = 'abcdef1234567'")
}

func TestStoreGetMissing(t *testing.T) {
	ctx := testctx.NewCtx()
	store := upstreamcommit.NewStore(ctx.FS(), testStoreDir)

	commit, exists, err := store.Get("missing")
	require.NoError(t, err)
	assert.False(t, exists)
	assert.Empty(t, commit)
}

func TestStoreExistsAndRemove(t *testing.T) {
	ctx := testctx.NewCtx()
	store := upstreamcommit.NewStore(ctx.FS(), testStoreDir)

	exists, err := store.Exists("bash")
	require.NoError(t, err)
	assert.False(t, exists)

	require.NoError(t, store.Save("bash", "abcdef1234567"))
	exists, err = store.Exists("bash")
	require.NoError(t, err)
	assert.True(t, exists)

	removed, err := store.Remove("bash")
	require.NoError(t, err)
	assert.True(t, removed)

	removed, err = store.Remove("bash")
	require.NoError(t, err)
	assert.False(t, removed)
}

func TestStoreRejectsInvalidComponentName(t *testing.T) {
	ctx := testctx.NewCtx()
	store := upstreamcommit.NewStore(ctx.FS(), testStoreDir)

	_, err := store.Path("../outside")
	require.Error(t, err)
	_, err = store.Exists("../outside")
	require.Error(t, err)
	_, err = store.Remove("../outside")
	require.Error(t, err)
	require.Error(t, store.Save("../outside", "abcdef1"))
}

func TestStoreGetReportsInvalidTOMLAndSaveReplacesIt(t *testing.T) {
	ctx := testctx.NewCtx()
	store := upstreamcommit.NewStore(ctx.FS(), testStoreDir)
	path := filepath.Join(testStoreDir, "bash.toml")
	require.NoError(t, fileutils.MkdirAll(ctx.FS(), testStoreDir))
	require.NoError(t, fileutils.WriteFile(ctx.FS(), path, []byte("invalid = ["), fileperms.PublicFile))

	_, exists, err := store.Get("bash")
	assert.True(t, exists)
	require.ErrorContains(t, err, "parsing upstream commit TOML")

	require.NoError(t, store.Save("bash", "abcdef1"))
	commit, exists, err := store.Get("bash")
	require.NoError(t, err)
	assert.True(t, exists)
	assert.Equal(t, "abcdef1", commit)
}

func TestStoreFindAndPruneOrphans(t *testing.T) {
	ctx := testctx.NewCtx()

	store := upstreamcommit.NewStore(ctx.FS(), testStoreDir)
	for _, name := range []string{"kept", "local", "removed"} {
		require.NoError(t, store.Save(name, "abcdef1"))
	}

	components := map[string]projectconfig.ComponentConfig{
		"kept": {
			Spec: projectconfig.SpecSource{SourceType: projectconfig.SpecSourceTypeUpstream},
		},
		"local": {
			Spec: projectconfig.SpecSource{SourceType: projectconfig.SpecSourceTypeLocal},
		},
	}

	orphans, err := store.FindOrphans(components)
	require.NoError(t, err)
	assert.Equal(t, []string{"local", "removed"}, orphans)

	pruned, err := store.PruneOrphans(components)
	require.NoError(t, err)
	assert.Equal(t, 2, pruned)

	_, exists, err := store.Get("kept")
	require.NoError(t, err)
	assert.True(t, exists)
	_, exists, err = store.Get("removed")
	require.NoError(t, err)
	assert.False(t, exists)
}
