// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: spec.go
//
// Generated by this command:
//
//	mockgen -source=spec.go -destination=specs_testutils/spec_mocks.go -package=specs_testutils --copyright_file=../../../../../.license-preamble
//

// Package specs_testutils is a generated GoMock package.
package specs_testutils

import (
	reflect "reflect"

	specs "github.com/microsoft/azure-linux-dev-tools/internal/app/azldev/core/specs"
	gomock "go.uber.org/mock/gomock"
)

// MockComponentSpec is a mock of ComponentSpec interface.
type MockComponentSpec struct {
	ctrl     *gomock.Controller
	recorder *MockComponentSpecMockRecorder
	isgomock struct{}
}

// MockComponentSpecMockRecorder is the mock recorder for MockComponentSpec.
type MockComponentSpecMockRecorder struct {
	mock *MockComponentSpec
}

// NewMockComponentSpec creates a new mock instance.
func NewMockComponentSpec(ctrl *gomock.Controller) *MockComponentSpec {
	mock := &MockComponentSpec{ctrl: ctrl}
	mock.recorder = &MockComponentSpecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponentSpec) EXPECT() *MockComponentSpecMockRecorder {
	return m.recorder
}

// GetPath mocks base method.
func (m *MockComponentSpec) GetPath() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPath")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPath indicates an expected call of GetPath.
func (mr *MockComponentSpecMockRecorder) GetPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPath", reflect.TypeOf((*MockComponentSpec)(nil).GetPath))
}

// Parse mocks base method.
func (m *MockComponentSpec) Parse() (*specs.ComponentSpecDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse")
	ret0, _ := ret[0].(*specs.ComponentSpecDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockComponentSpecMockRecorder) Parse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockComponentSpec)(nil).Parse))
}
