// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: rpmprovider.go
//
// Generated by this command:
//
//	mockgen -source=rpmprovider.go -destination=rpmprovider_test/rpmprovider_mocks.go -package=rpmprovider_test --copyright_file=../../../.license-preamble
//

// Package rpmprovider_test is a generated GoMock package.
package rpmprovider_test

import (
	context "context"
	io "io"
	reflect "reflect"

	rpm "github.com/microsoft/azure-linux-dev-tools/internal/rpm"
	gomock "go.uber.org/mock/gomock"
)

// MockRPMProvider is a mock of RPMProvider interface.
type MockRPMProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRPMProviderMockRecorder
	isgomock struct{}
}

// MockRPMProviderMockRecorder is the mock recorder for MockRPMProvider.
type MockRPMProviderMockRecorder struct {
	mock *MockRPMProvider
}

// NewMockRPMProvider creates a new mock instance.
func NewMockRPMProvider(ctrl *gomock.Controller) *MockRPMProvider {
	mock := &MockRPMProvider{ctrl: ctrl}
	mock.recorder = &MockRPMProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPMProvider) EXPECT() *MockRPMProviderMockRecorder {
	return m.recorder
}

// GetRPM mocks base method.
func (m *MockRPMProvider) GetRPM(ctx context.Context, name string, version *rpm.Version) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRPM", ctx, name, version)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRPM indicates an expected call of GetRPM.
func (mr *MockRPMProviderMockRecorder) GetRPM(ctx, name, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRPM", reflect.TypeOf((*MockRPMProvider)(nil).GetRPM), ctx, name, version)
}
