blank_issues_enabled: false
contact_links:
  - name: Azure Linux distro issues
    url: https://github.com/microsoft/azurelinux/issues
    about: "For issues with Azure Linux itself (for example: distro packages, kernel, base image content), please file in the azurelinux repo."
