// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package config

import (
	"encoding/json"
	"fmt"

	"github.com/invopop/jsonschema"
	"github.com/microsoft/azure-linux-dev-tools/internal/app/azldev"
	"github.com/microsoft/azure-linux-dev-tools/internal/projectconfig"
	"github.com/spf13/cobra"
)

// Called once when the app is initialized; registers any commands or callbacks with the app.
func generateSchemaOnAppInit(_ *azldev.App, parentCmd *cobra.Command) {
	parentCmd.AddCommand(newConfigCmd())
}

func newConfigCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generate-schema",
		Short: "Generates JSON schema for validating .toml config files",
		Long: `Generate a JSON schema for the azldev TOML configuration file format.

The schema is printed to stdout and can be saved to a file for use with
editors or linters that support JSON Schema validation of TOML files.`,
		Example: `  # Print the schema to stdout
  azldev config generate-schema

  # Save the schema to a file
  azldev config generate-schema > schemas/azldev.schema.json`,
		RunE: func(cmd *cobra.Command, args []string) error {
			schemaText, err := GenerateAzlDevTOMLJSONSchema()
			if err != nil {
				return err
			}

			fmt.Println(schemaText)

			return nil
		},
	}

	azldev.ExportAsMCPTool(cmd)

	return cmd
}

// Generates a JSON schema (in string form) for the azldev.toml project configuration file format.
func GenerateAzlDevTOMLJSONSchema() (string, error) {
	// Set up a reflector that uses `toml` tags instead of `json` ones (the default).
	reflector := &jsonschema.Reflector{
		FieldNameTag: "toml",
	}

	schema := reflector.Reflect(projectconfig.ConfigFile{})

	schema.Comments = "This schema was auto-generated by: azldev config generate-schema"

	jsonBytes, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return "", fmt.Errorf("failed to serialize schema:\n%w", err)
	}

	return string(jsonBytes), nil
}
