// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package sources

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"path/filepath"
	"slices"
	"strings"
	"unicode"

	gogit "github.com/go-git/go-git/v5"
	"github.com/microsoft/azure-linux-dev-tools/internal/app/azldev/core/components"
	"github.com/microsoft/azure-linux-dev-tools/internal/global/opctx"
	"github.com/microsoft/azure-linux-dev-tools/internal/projectconfig"
	"github.com/microsoft/azure-linux-dev-tools/internal/providers/sourceproviders"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/dirdiff"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/fileperms"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/fileutils"
	"github.com/samber/lo"
	"go.szostok.io/version"
)

// MacrosFileExtension is the file extension used for azldev-generated macros files.
const MacrosFileExtension = ".azl.macros"

// MacrosFileHeader is the comment header included at the top of generated macros files.
const MacrosFileHeader = `# Macros file automatically generated by azldev.
# Do not edit manually; changes will be overwritten.`

// SourcePreparer is a utility for acquiring and preparing all input files required to build a component.
// This may include the component's spec file, any loose files that must accompany it, any payload source
// archives and patches required by the spec, etc. Preparation may also include any post-processing of these
// inputs to match the component's configuration within the containing project.
type SourcePreparer interface {
	// PrepareSources prepares the input sources for the given component, writing them to the given output directory.
	// After this function completes successfully, the output directory should contain all files required to build
	// the component, with any post-processing applied as necessary. The only remaining dependencies not contained
	// within the output directory will be build-time dependencies on external packages (RPMs), including those
	// relied on to be present implicitly within the build root, or expressed via BuildRequires or DynamicBuildRequires
	// in the component's spec file and any defaults from the macros used to interpret the spec file.
	PrepareSources(ctx context.Context, component components.Component, outputDir string, applyOverlays bool) error

	// DiffSources computes a unified diff showing the changes that overlays apply to a component's sources.
	// The component's sources are fetched once into a subdirectory of baseDir, then copied to a second
	// subdirectory where overlays are applied in-place. The diff between the two subdirectories is returned.
	DiffSources(ctx context.Context, component components.Component, baseDir string) (*dirdiff.DiffResult, error)
}

// Standard implementation of the [SourcePreparer] interface.
type sourcePreparerImpl struct {
	sourceManager sourceproviders.SourceManager
	fs            opctx.FS
	eventListener opctx.EventListener
	dryRunnable   opctx.DryRunnable
}

// NewPreparer creates a new [SourcePreparer] instance. All arguments are required.
func NewPreparer(
	sourceManager sourceproviders.SourceManager,
	fs opctx.FS,
	eventListener opctx.EventListener,
	dryRunnable opctx.DryRunnable,
) (SourcePreparer, error) {
	if sourceManager == nil {
		return nil, errors.New("source manager cannot be nil")
	}

	if fs == nil {
		return nil, errors.New("filesystem interface cannot be nil")
	}

	if eventListener == nil {
		return nil, errors.New("event listener interface cannot be nil")
	}

	if dryRunnable == nil {
		return nil, errors.New("dry runnable interface cannot be nil")
	}

	impl := &sourcePreparerImpl{
		sourceManager: sourceManager,
		fs:            fs,
		eventListener: eventListener,
		dryRunnable:   dryRunnable,
	}

	return impl, nil
}

// PrepareSources implements the [SourcePreparer] interface.
func (p *sourcePreparerImpl) PrepareSources(
	ctx context.Context, component components.Component, outputDir string, applyOverlays bool,
) error {
	// Use the source manager to fetch source files (archives, patches, etc.)
	err := p.sourceManager.FetchFiles(ctx, component, outputDir)
	if err != nil {
		return fmt.Errorf("failed to fetch source files for component %#q:\n%w",
			component.GetName(), err)
	}

	// Preserve the upstream .git directory when overlays will be applied. This is
	// required so that overlay commits can be appended on top of the upstream commit
	// log during synthetic history generation.
	var fetchOpts []sourceproviders.FetchComponentOption
	if applyOverlays {
		fetchOpts = append(fetchOpts, sourceproviders.WithPreserveGitDir())
	}

	// Use the source manager to fetch the component (spec file and sidecar files).
	err = p.sourceManager.FetchComponent(ctx, component, outputDir, fetchOpts...)
	if err != nil {
		return fmt.Errorf("failed to fetch sources for component %#q:\n%w",
			component.GetName(), err)
	}

	if !applyOverlays {
		return nil
	}

	return p.applyOverlaysToSources(ctx, component, outputDir)
}

// applyOverlaysToSources writes the macros file and then applies overlays using either the
// synthetic history path or the standard postProcessSources path.
func (p *sourcePreparerImpl) applyOverlaysToSources(
	ctx context.Context, component components.Component, outputDir string,
) error {
	// Emit computed macros to a macros file in the output directory.
	// If the build configuration produces no macros, no file is written and
	// macrosFileName will be empty, signaling postProcessSources to skip
	// injecting the macro load directive and Source9999 tag.
	var macrosFileName string

	macrosFilePath, err := p.writeMacrosFile(component, outputDir)
	if err != nil {
		return fmt.Errorf("failed to write macros file for component %#q:\n%w",
			component.GetName(), err)
	}

	if macrosFilePath != "" {
		macrosFileName = filepath.Base(macrosFilePath)
	}

	// Apply user-defined overlays as attributed synthetic git commits, then apply
	// system overlays separately. If synthetic history cannot be generated (e.g. no
	// git repo available), applyOverlaysWithHistory falls back to the standard path.
	err = p.applyOverlaysWithHistory(ctx, component, outputDir, macrosFileName)
	if err != nil {
		return fmt.Errorf("failed to post-process sources for component %q:\n%w", component.GetName(), err)
	}

	return nil
}

// applyOverlaysWithHistory applies user-defined overlays as attributed synthetic git
// commits in the upstream repository, then applies system overlays (macros, check-skip,
// header) outside of the synthetic history so they don't pollute blame attribution.
//
// When the sources directory does not contain a git repository (e.g. local or unspecified
// spec sources), the function falls back to applying overlays sequentially without history.
func (p *sourcePreparerImpl) applyOverlaysWithHistory(
	_ context.Context, component components.Component, sourcesDirPath, macrosFileName string,
) error {
	event := p.eventListener.StartEvent("Applying overlays", "component", component.GetName())
	defer event.End()

	// Resolve the spec path once for all overlay operations in this call.
	absSpecPath, err := p.resolveSpecPath(component, sourcesDirPath)
	if err != nil {
		return err
	}

	config := component.GetConfig()
	if len(config.Overlays) == 0 {
		slog.Debug("No overlays defined; skipping synthetic history generation",
			"component", component.GetName())

		return p.applySystemOverlays(component, sourcesDirPath, absSpecPath, macrosFileName)
	}

	// Try the synthetic history path. If it succeeds, apply system overlays and return.
	if err := p.trySyntheticHistory(component, config, sourcesDirPath, absSpecPath); err == nil {
		return p.applySystemOverlays(component, sourcesDirPath, absSpecPath, macrosFileName)
	}

	// Synthetic history was not possible; apply user overlays sequentially.
	if err := p.applyOverlayList(config.Overlays, sourcesDirPath, absSpecPath); err != nil {
		return fmt.Errorf("failed to apply overlays for component %#q:\n%w", component.GetName(), err)
	}

	return p.applySystemOverlays(component, sourcesDirPath, absSpecPath, macrosFileName)
}

// trySyntheticHistory attempts to apply user-defined overlays as synthetic git commits.
// Returns nil on success, or a non-nil error if the synthetic history path is not available
// (e.g. no .git directory, no resolvable blame groups). The caller should fall back to
// sequential overlay application when this returns an error.
func (p *sourcePreparerImpl) trySyntheticHistory(
	component components.Component,
	config *projectconfig.ComponentConfig,
	sourcesDirPath, absSpecPath string,
) error {
	// Check for an upstream git repository in the sources directory. Local and
	// unspecified spec sources won't have a .git directory.
	gitDirPath := filepath.Join(sourcesDirPath, ".git")
	if _, err := p.fs.Stat(gitDirPath); err != nil {
		slog.Debug("No .git directory in sources; falling back to standard overlay path",
			"component", component.GetName(),
			"sourcesDirPath", sourcesDirPath)

		return fmt.Errorf("no .git directory in sources dir %#q:\n%w", sourcesDirPath, err)
	}

	// Resolve the project repository and blame the config file to produce overlay groups.
	groups, err := buildOverlayGroups(config, component.GetName())
	if err != nil {
		return fmt.Errorf("failed to build overlay groups:\n%w", err)
	}

	if len(groups) == 0 {
		return errors.New("no overlay groups resolved")
	}

	// Open the upstream git repository where synthetic commits will be recorded.
	sourcesRepo, err := gogit.PlainOpen(sourcesDirPath)
	if err != nil {
		return fmt.Errorf("failed to open upstream repository at %#q:\n%w", sourcesDirPath, err)
	}

	// Build the overlay-application callback using the shared helper.
	applyFn := func(overlays []projectconfig.ComponentOverlay) error {
		return p.applyOverlayList(overlays, sourcesDirPath, absSpecPath)
	}

	if err := CommitSyntheticHistory(sourcesRepo, groups, applyFn); err != nil {
		return fmt.Errorf("failed to commit synthetic history:\n%w", err)
	}

	return nil
}

// applySystemOverlays applies the macros-load, check-skip, and file-header overlays that
// are synthesized at build time rather than defined in the project TOML config.
func (p *sourcePreparerImpl) applySystemOverlays(
	component components.Component, sourcesDirPath, absSpecPath, macrosFileName string,
) error {
	// Collect all system overlays in application order: macros, check-skip, file header.
	var systemOverlays []projectconfig.ComponentOverlay

	if macrosFileName != "" {
		macroOverlays, macroErr := synthesizeMacroLoadOverlays(macrosFileName)
		if macroErr != nil {
			return fmt.Errorf("failed to compute macros load overlays:\n%w", macroErr)
		}

		systemOverlays = append(systemOverlays, macroOverlays...)
	}

	systemOverlays = append(systemOverlays, synthesizeCheckSkipOverlays(component.GetConfig().Build.Check)...)
	systemOverlays = append(systemOverlays, generateFileHeaderOverlay()...)

	return p.applyOverlayList(systemOverlays, sourcesDirPath, absSpecPath)
}

// DiffSources implements the [SourcePreparer] interface.
// It fetches the component's sources once, copies them to a second directory, applies overlays
// to the copy, then diffs the two trees. This avoids fetching the sources twice.
func (p *sourcePreparerImpl) DiffSources(
	ctx context.Context, component components.Component, baseDir string,
) (result *dirdiff.DiffResult, err error) {
	event := p.eventListener.StartEvent("Computing overlay diff", "component", component.GetName())
	defer event.End()

	// Create temp dirs for sources prepared without and with overlays.
	originalDir, err := fileutils.MkdirTemp(p.fs, baseDir, "original-")
	if err != nil {
		return nil, fmt.Errorf("failed to create temp dir for original sources:\n%w", err)
	}

	defer fileutils.RemoveAllAndUpdateErrorIfNil(p.fs, originalDir, &err)

	// Prepare sources without applying overlays, to get the original tree.
	if err := p.PrepareSources(ctx, component, originalDir, false /* applyOverlays */); err != nil {
		return nil, err
	}

	// Copy the fetched sources to a separate directory for in-place overlay application.
	// This avoids a second network fetch.
	overlaidDir, err := fileutils.MkdirTemp(p.fs, baseDir, "overlaid-")
	if err != nil {
		return nil, fmt.Errorf("failed to create temp dir for overlaid sources:\n%w", err)
	}

	defer fileutils.RemoveAllAndUpdateErrorIfNil(p.fs, overlaidDir, &err)

	if err := fileutils.CopyDirRecursive(
		p.dryRunnable, p.fs, originalDir, overlaidDir,
		fileutils.CopyDirOptions{CopyFileOptions: fileutils.CopyFileOptions{PreserveFileMode: true}},
	); err != nil {
		return nil, fmt.Errorf("failed to copy sources for component %#q:\n%w", component.GetName(), err)
	}

	// Apply overlays in-place to the copied directory only.
	var macrosFileName string

	macrosFilePath, err := p.writeMacrosFile(component, overlaidDir)
	if err != nil {
		return nil, fmt.Errorf("failed to write macros file for component %#q:\n%w", component.GetName(), err)
	}

	if macrosFilePath != "" {
		macrosFileName = filepath.Base(macrosFilePath)
	}

	if err := p.postProcessSources(component, overlaidDir, macrosFileName); err != nil {
		return nil, fmt.Errorf("failed to post-process sources for component %#q:\n%w", component.GetName(), err)
	}

	// Diff the original tree against the overlaid tree.
	result, err = dirdiff.DiffDirs(p.fs, originalDir, overlaidDir)
	if err != nil {
		return nil, fmt.Errorf("failed to diff source trees for component %#q:\n%w",
			component.GetName(), err)
	}

	return result, nil
}

// writeMacrosFile writes a macros file containing the resolved macros for a component.
// This includes with/without flags converted to macro format, and any explicit defines.
// If the build configuration produces no macros, no file is written and an empty path is
// returned. Otherwise, the path to the written macros file is returned.
func (p *sourcePreparerImpl) writeMacrosFile(component components.Component, outputDir string) (string, error) {
	contents := GenerateMacrosFileContents(component.GetConfig().Build)
	if contents == "" {
		return "", nil
	}

	macrosFilePath := filepath.Join(outputDir, component.GetName()+MacrosFileExtension)

	err := fileutils.WriteFile(p.fs, macrosFilePath, []byte(contents), fileperms.PublicFile)
	if err != nil {
		return "", fmt.Errorf("failed to write macros file %#q:\n%w", macrosFilePath, err)
	}

	return macrosFilePath, nil
}

// GenerateMacrosFileContents generates the contents of an RPM macros file from the given
// build configuration. The output uses standard RPM macro file format (%name value) and
// includes a header comment identifying the file as auto-generated.
//
// With flags are converted to %_with_FLAG 1 macros.
// Without flags are converted to %_without_FLAG 1 macros.
// Defines are emitted as %name value macros.
//
// All macros are collected into a single map and sorted alphabetically by name for
// deterministic output. If the same macro is defined multiple times (e.g., via both
// a with flag and an explicit define), the later definition wins. The order of processing
// is: with flags, then without flags, then explicit defines, then undefines.
//
// Undefines remove entries from the generated macros map. This only affects macros that
// originate from the merged TOML configuration (with, without, and defines fields); it
// does not undefine arbitrary system-level RPM macros. The primary use case is allowing
// a component-level TOML file to override a distro-level or project-level default by
// removing a macro that would otherwise be emitted into the macros file.
//
// Note: RPM macro values can contain spaces without special escaping; everything
// after the macro name (and separating whitespace) is treated as the macro body.
//
// If no macros remain after processing (empty config, or all macros removed via
// undefines), an empty string is returned to signal that no macros file is needed.
func GenerateMacrosFileContents(buildConfig projectconfig.ComponentBuildConfig) string {
	// Build a unified map of all macros. Later definitions override earlier ones.
	// Processing order: with flags -> without flags -> explicit defines.
	macros := make(map[string]string)

	// Convert 'with' flags to macros: FLAG -> _with_FLAG = 1
	for _, with := range buildConfig.With {
		macros["_with_"+with] = "1"
	}

	// Convert 'without' flags to macros: FLAG -> _without_FLAG = 1
	for _, without := range buildConfig.Without {
		macros["_without_"+without] = "1"
	}

	// Add explicit macro definitions (these override any conflicting with/without flags).
	for name, value := range buildConfig.Defines {
		macros[name] = value
	}

	// Remove any macros listed in undefines. This allows component-level config to
	// override distro-level default macro definitions by removing them entirely.
	for _, undef := range buildConfig.Undefines {
		delete(macros, undef)
	}

	if len(macros) == 0 {
		return ""
	}

	lines := []string{
		MacrosFileHeader,
	}

	// Sort macro names for deterministic output.
	macroNames := lo.Keys(macros)
	slices.Sort(macroNames)

	for _, name := range macroNames {
		lines = append(lines, fmt.Sprintf("%%%s %s", name, macros[name]))
	}

	return strings.Join(lines, "\n") + "\n"
}

func synthesizeMacroLoadOverlays(macrosFileName string) ([]projectconfig.ComponentOverlay, error) {
	// Basic check that the macros file name is valid and doesn't require escaping.
	if strings.ContainsFunc(macrosFileName, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '.' && r != '-' && r != '_' && r != '+'
	}) {
		return nil, fmt.Errorf(
			"macros file name %#q contains invalid characters; does the component name contain invalid characters?",
			macrosFileName,
		)
	}

	// We inject an overlay to prepend a line to the spec to load the macros file.
	return []projectconfig.ComponentOverlay{
		{
			// Prepend the %{load:...} directive to the spec.
			Type: projectconfig.ComponentOverlayPrependSpecLines,
			Lines: []string{
				"# All Azure Linux specs with overlays include this macro file, irrespective of" +
					" whether new macros have been added.",
				fmt.Sprintf("%%{load:%%{_sourcedir}/%s}", macrosFileName),
				"",
			},
		},
		{
			// Ensure that the macros file is manifested as a source in the spec so that
			// mock and other tools know it needs to be present in the build root.
			// Use InsertSpecTag to place it after the last existing Source* tag, avoiding
			// misplacement after macros like %fontpkg or inside %if conditionals.
			Type:  projectconfig.ComponentOverlayInsertSpecTag,
			Tag:   "Source9999", // Use a high number to avoid conflicts with existing sources.
			Value: macrosFileName,
		},
	}, nil
}

// generateFileHeaderOverlay generates an overlay that prepends a header to the spec.
// It should be applied after all other overlays, as it should be the first thing in the spec file.
func generateFileHeaderOverlay() []projectconfig.ComponentOverlay {
	ver := version.Get()

	return []projectconfig.ComponentOverlay{
		{
			Type: projectconfig.ComponentOverlayPrependSpecLines,
			Lines: []string{
				"# This spec file has been modified by azldev to include build configuration overlays. Version: " + ver.Version,
				"# Do not edit manually; changes may be overwritten.",
				"",
			},
		},
	}
}

// synthesizeCheckSkipOverlays generates overlays to disable the %check section if configured.
// When check.skip is true, it prepends an 'exit 0' to the %check section with a comment
// explaining why the section was disabled.
func synthesizeCheckSkipOverlays(checkConfig projectconfig.CheckConfig) []projectconfig.ComponentOverlay {
	if !checkConfig.Skip {
		return nil
	}

	return []projectconfig.ComponentOverlay{
		{
			Type:        projectconfig.ComponentOverlayPrependSpecLines,
			SectionName: "%check",
			Lines: []string{
				"# Check section disabled: " + checkConfig.SkipReason,
				"exit 0",
				"",
			},
		},
	}
}

// resolveSpecPath locates and returns the absolute path to the component's spec file
// within the given sources directory.
func (p *sourcePreparerImpl) resolveSpecPath(
	component components.Component, sourcesDirPath string,
) (string, error) {
	specPath, err := findSpecInDir(p.fs, component, sourcesDirPath)
	if err != nil {
		return "", fmt.Errorf("failed to find spec in sources dir %#q:\n%w", sourcesDirPath, err)
	}

	absSpecPath, err := filepath.Abs(specPath)
	if err != nil {
		return "", fmt.Errorf("failed to get absolute path for spec %#q:\n%w", specPath, err)
	}

	return absSpecPath, nil
}

// applyOverlayList applies a list of overlays to the component sources sequentially.
func (p *sourcePreparerImpl) applyOverlayList(
	overlays []projectconfig.ComponentOverlay, sourcesDirPath, absSpecPath string,
) error {
	for _, overlay := range overlays {
		if err := ApplyOverlayToSources(
			p.dryRunnable, p.fs, overlay, sourcesDirPath, absSpecPath,
		); err != nil {
			return fmt.Errorf("failed to apply %#q overlay:\n%w", overlay.Type, err)
		}
	}

	return nil
}

func findSpecInDir(
	fs opctx.FS, component components.Component, dirPath string,
) (string, error) {
	specPath := filepath.Join(dirPath, component.GetName()+".spec")

	if _, statErr := fs.Stat(specPath); statErr != nil {
		return specPath, fmt.Errorf("failed to find spec for component %#q in %#q:\n%w",
			component.GetName(), dirPath, statErr,
		)
	}

	return specPath, nil
}
