// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package docs

import (
	"fmt"
	"regexp"

	"github.com/microsoft/azure-linux-dev-tools/internal/app/azldev"
	"github.com/microsoft/azure-linux-dev-tools/internal/global/opctx"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/fileutils"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

type GenerateMarkdownOptions struct {
	OutputDir     string
	IncludeHidden bool
	Force         bool
}

// Called once when the app is initialized; registers any commands or callbacks with the app.
func mdOnAppInit(_ *azldev.App, parentCmd *cobra.Command) {
	parentCmd.AddCommand(newMarkdownCmd())
}

func newMarkdownCmd() *cobra.Command {
	var options GenerateMarkdownOptions

	cmd := &cobra.Command{
		Use:     "markdown",
		Aliases: []string{"md"},
		Short:   "Generates Markdown (.md) docs for this tool",
		Long: `Generate Markdown reference documentation for all azldev CLI commands.

Produces one .md file per command in the output directory. These files are
auto-generated and should not be hand-edited; update the Cobra command
definitions in Go source code instead, then re-run this command.`,
		Example: `  # Generate docs into the user guide
  azldev docs markdown -o docs/user/reference/cli/

  # Include hidden (advanced) commands
  azldev docs markdown -o docs/user/reference/cli/ --include-hidden

  # Overwrite an existing non-empty output directory
  azldev docs markdown -o docs/user/reference/cli/ -f`,
	}

	cmd.RunE = azldev.RunFuncWithoutRequiredConfig(
		func(env *azldev.Env) (interface{}, error) {
			return nil, GenerateMarkdownDocs(env.FS(), cmd.Root(), &options)
		})

	cmd.Flags().StringVarP(&options.OutputDir, "output-dir", "o", "", "directory markdown files will be written to")
	cmd.Flags().BoolVarP(&options.Force, "force", "f", false,
		"delete and recreate the output directory if it already exists")
	cmd.Flags().BoolVar(&options.IncludeHidden, "include-hidden", false, "include hidden commands in the generated docs")

	// NOTE: we ignore errors because we don't expect that they could fail at runtime, and because this function
	// is expected to be infallible.
	_ = cmd.MarkFlagRequired("output-dir")
	_ = cmd.MarkFlagDirname("output-dir")

	azldev.ExportAsMCPTool(cmd)

	return cmd
}

const generatedFileHeader = `<!--- DO NOT EDIT: auto-generated by "azldev docs markdown" -->` + "\n\n"

// filePrepender returns a function that prepends the auto-generated header to each generated doc file.
func filePrepender(_ string) string {
	return generatedFileHeader
}

// linkHandler converts cobra doc filenames to relative markdown file links.
// Cobra passes in filenames like "azldev_component.md"; since each command gets
// its own file we link directly to that file rather than using a fragment anchor.
func linkHandler(name string) string {
	return name
}

// versionSuffix matches a trailing version string like " v1.2.3" or " v0.0.0-20260228210254-10ca5c6a64fb".
var versionSuffix = regexp.MustCompile(` v\S+$`)

// stripVersionFromShort removes the trailing version string from the root command's
// Short description so that generated docs don't change with every build.
func stripVersionFromShort(short string) string {
	return versionSuffix.ReplaceAllString(short, "")
}

// setHiddenRecursive sets or clears the [cobra.Command.Hidden] flag on a command and all its children.
func setHiddenRecursive(cmd *cobra.Command, hidden bool) {
	cmd.Hidden = hidden

	for _, child := range cmd.Commands() {
		setHiddenRecursive(child, hidden)
	}
}

// CheckOutputDir verifies the output directory state before generation.
// If the directory exists and is non-empty, it either removes it (when Force is set)
// or returns an actionable error suggesting --force / -f.
func CheckOutputDir(fs opctx.FS, options *GenerateMarkdownOptions) error {
	dirExists, err := fileutils.DirExists(fs, options.OutputDir)
	if err != nil {
		return fmt.Errorf("failed to check output directory %q:\n%w", options.OutputDir, err)
	}

	if !dirExists {
		return nil
	}

	empty, err := fileutils.IsDirEmpty(fs, options.OutputDir)
	if err != nil {
		return fmt.Errorf("failed to check if output directory %q is empty:\n%w", options.OutputDir, err)
	}

	if empty {
		return nil
	}

	if options.Force {
		if err := fs.RemoveAll(options.OutputDir); err != nil {
			return fmt.Errorf("failed to clean output directory %q:\n%w", options.OutputDir, err)
		}

		return nil
	}

	return fmt.Errorf(
		"output directory %q already exists and is not empty;\n"+
			"use --force / -f to delete and recreate it",
		options.OutputDir)
}

// GenerateMarkdownDocs generates markdown documentation for the given command tree.
func GenerateMarkdownDocs(fs opctx.FS, rootCmd *cobra.Command, options *GenerateMarkdownOptions) error {
	// Strip the dynamic version string from the root command's Short description and disable
	// the auto-generated date footer so that generated docs don't churn on every build.
	origShort := rootCmd.Short
	rootCmd.Short = stripVersionFromShort(origShort)
	rootCmd.DisableAutoGenTag = true

	defer func() {
		rootCmd.Short = origShort
		rootCmd.DisableAutoGenTag = false
	}()

	// Check the output directory state and handle force semantics.
	err := CheckOutputDir(fs, options)
	if err != nil {
		return err
	}

	// Make sure the directory exists (it may have been removed by checkOutputDir, or may not exist yet).
	err = fileutils.MkdirAll(fs, options.OutputDir)
	if err != nil {
		return fmt.Errorf("failed to ensure output directory %q exists:\n%w", options.OutputDir, err)
	}

	if options.IncludeHidden {
		// Unhide all commands so they appear in the generated docs.
		setHiddenRecursive(rootCmd, false)
	}

	// NOTE: This function can't work with our [opctx.FS] filesystem abstraction, but there's not much
	// we can do about that.
	err = doc.GenMarkdownTreeCustom(rootCmd, options.OutputDir, filePrepender, linkHandler)
	if err != nil {
		return fmt.Errorf("failed to generate markdown docs:\n%w", err)
	}

	return nil
}
