// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/microsoft/azure-linux-dev-tools/internal/providers/sourceproviders (interfaces: SourceManager)
//
// Generated by this command:
//
//	mockgen -package=sourceproviders_test -destination=sourceproviders_test/sourcemanager_mocks.go github.com/microsoft/azure-linux-dev-tools/internal/providers/sourceproviders SourceManager
//

// Package sourceproviders_test is a generated GoMock package.
package sourceproviders_test

import (
	context "context"
	reflect "reflect"

	components "github.com/microsoft/azure-linux-dev-tools/internal/app/azldev/core/components"
	gomock "go.uber.org/mock/gomock"
)

// MockSourceManager is a mock of SourceManager interface.
type MockSourceManager struct {
	ctrl     *gomock.Controller
	recorder *MockSourceManagerMockRecorder
	isgomock struct{}
}

// MockSourceManagerMockRecorder is the mock recorder for MockSourceManager.
type MockSourceManagerMockRecorder struct {
	mock *MockSourceManager
}

// NewMockSourceManager creates a new mock instance.
func NewMockSourceManager(ctrl *gomock.Controller) *MockSourceManager {
	mock := &MockSourceManager{ctrl: ctrl}
	mock.recorder = &MockSourceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceManager) EXPECT() *MockSourceManagerMockRecorder {
	return m.recorder
}

// FetchComponent mocks base method.
func (m *MockSourceManager) FetchComponent(ctx context.Context, component components.Component, destDirPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchComponent", ctx, component, destDirPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchComponent indicates an expected call of FetchComponent.
func (mr *MockSourceManagerMockRecorder) FetchComponent(ctx, component, destDirPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchComponent", reflect.TypeOf((*MockSourceManager)(nil).FetchComponent), ctx, component, destDirPath)
}

// FetchFiles mocks base method.
func (m *MockSourceManager) FetchFiles(ctx context.Context, component components.Component, destDirPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFiles", ctx, component, destDirPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchFiles indicates an expected call of FetchFiles.
func (mr *MockSourceManagerMockRecorder) FetchFiles(ctx, component, destDirPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFiles", reflect.TypeOf((*MockSourceManager)(nil).FetchFiles), ctx, component, destDirPath)
}
