// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: buildenv.go
//
// Generated by this command:
//
//	mockgen -source=buildenv.go -destination=buildenv_testutils/buildenv_mocks.go -package=buildenv_testutils --copyright_file=../../.license-preamble
//

// Package buildenv_testutils is a generated GoMock package.
package buildenv_testutils

import (
	context "context"
	reflect "reflect"

	buildenv "github.com/microsoft/azure-linux-dev-tools/internal/buildenv"
	opctx "github.com/microsoft/azure-linux-dev-tools/internal/global/opctx"
	gomock "go.uber.org/mock/gomock"
)

// MockBuildEnv is a mock of BuildEnv interface.
type MockBuildEnv struct {
	ctrl     *gomock.Controller
	recorder *MockBuildEnvMockRecorder
	isgomock struct{}
}

// MockBuildEnvMockRecorder is the mock recorder for MockBuildEnv.
type MockBuildEnvMockRecorder struct {
	mock *MockBuildEnv
}

// NewMockBuildEnv creates a new mock instance.
func NewMockBuildEnv(ctrl *gomock.Controller) *MockBuildEnv {
	mock := &MockBuildEnv{ctrl: ctrl}
	mock.recorder = &MockBuildEnvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildEnv) EXPECT() *MockBuildEnvMockRecorder {
	return m.recorder
}

// CreateCmd mocks base method.
func (m *MockBuildEnv) CreateCmd(ctx context.Context, args []string, options buildenv.RunOptions) (opctx.Cmd, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCmd", ctx, args, options)
	ret0, _ := ret[0].(opctx.Cmd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCmd indicates an expected call of CreateCmd.
func (mr *MockBuildEnvMockRecorder) CreateCmd(ctx, args, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCmd", reflect.TypeOf((*MockBuildEnv)(nil).CreateCmd), ctx, args, options)
}

// Destroy mocks base method.
func (m *MockBuildEnv) Destroy(ctx opctx.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockBuildEnvMockRecorder) Destroy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockBuildEnv)(nil).Destroy), ctx)
}

// GetInfo mocks base method.
func (m *MockBuildEnv) GetInfo() buildenv.BuildEnvInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo")
	ret0, _ := ret[0].(buildenv.BuildEnvInfo)
	return ret0
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockBuildEnvMockRecorder) GetInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockBuildEnv)(nil).GetInfo))
}

// MockRPMAwareBuildEnv is a mock of RPMAwareBuildEnv interface.
type MockRPMAwareBuildEnv struct {
	ctrl     *gomock.Controller
	recorder *MockRPMAwareBuildEnvMockRecorder
	isgomock struct{}
}

// MockRPMAwareBuildEnvMockRecorder is the mock recorder for MockRPMAwareBuildEnv.
type MockRPMAwareBuildEnvMockRecorder struct {
	mock *MockRPMAwareBuildEnv
}

// NewMockRPMAwareBuildEnv creates a new mock instance.
func NewMockRPMAwareBuildEnv(ctrl *gomock.Controller) *MockRPMAwareBuildEnv {
	mock := &MockRPMAwareBuildEnv{ctrl: ctrl}
	mock.recorder = &MockRPMAwareBuildEnvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPMAwareBuildEnv) EXPECT() *MockRPMAwareBuildEnvMockRecorder {
	return m.recorder
}

// BuildRPM mocks base method.
func (m *MockRPMAwareBuildEnv) BuildRPM(ctx context.Context, srpmPath, outputDirPath string, options buildenv.RPMBuildOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildRPM", ctx, srpmPath, outputDirPath, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildRPM indicates an expected call of BuildRPM.
func (mr *MockRPMAwareBuildEnvMockRecorder) BuildRPM(ctx, srpmPath, outputDirPath, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildRPM", reflect.TypeOf((*MockRPMAwareBuildEnv)(nil).BuildRPM), ctx, srpmPath, outputDirPath, options)
}

// BuildSRPM mocks base method.
func (m *MockRPMAwareBuildEnv) BuildSRPM(ctx context.Context, specPath, sourceDirPath, outputDirPath string, options buildenv.SRPMBuildOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildSRPM", ctx, specPath, sourceDirPath, outputDirPath, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildSRPM indicates an expected call of BuildSRPM.
func (mr *MockRPMAwareBuildEnvMockRecorder) BuildSRPM(ctx, specPath, sourceDirPath, outputDirPath, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildSRPM", reflect.TypeOf((*MockRPMAwareBuildEnv)(nil).BuildSRPM), ctx, specPath, sourceDirPath, outputDirPath, options)
}

// CreateCmd mocks base method.
func (m *MockRPMAwareBuildEnv) CreateCmd(ctx context.Context, args []string, options buildenv.RunOptions) (opctx.Cmd, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCmd", ctx, args, options)
	ret0, _ := ret[0].(opctx.Cmd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCmd indicates an expected call of CreateCmd.
func (mr *MockRPMAwareBuildEnvMockRecorder) CreateCmd(ctx, args, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCmd", reflect.TypeOf((*MockRPMAwareBuildEnv)(nil).CreateCmd), ctx, args, options)
}

// Destroy mocks base method.
func (m *MockRPMAwareBuildEnv) Destroy(ctx opctx.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockRPMAwareBuildEnvMockRecorder) Destroy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockRPMAwareBuildEnv)(nil).Destroy), ctx)
}

// GetInfo mocks base method.
func (m *MockRPMAwareBuildEnv) GetInfo() buildenv.BuildEnvInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo")
	ret0, _ := ret[0].(buildenv.BuildEnvInfo)
	return ret0
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockRPMAwareBuildEnvMockRecorder) GetInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockRPMAwareBuildEnv)(nil).GetInfo))
}

// TryGetFailureDetails mocks base method.
func (m *MockRPMAwareBuildEnv) TryGetFailureDetails(fs opctx.FS, outputDirPath string) *buildenv.RPMBuildLogDetails {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryGetFailureDetails", fs, outputDirPath)
	ret0, _ := ret[0].(*buildenv.RPMBuildLogDetails)
	return ret0
}

// TryGetFailureDetails indicates an expected call of TryGetFailureDetails.
func (mr *MockRPMAwareBuildEnvMockRecorder) TryGetFailureDetails(fs, outputDirPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryGetFailureDetails", reflect.TypeOf((*MockRPMAwareBuildEnv)(nil).TryGetFailureDetails), fs, outputDirPath)
}
