// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: factory.go
//
// Generated by this command:
//
//	mockgen -source=factory.go -destination=buildenv_testutils/factory_mocks.go -package=buildenv_testutils --copyright_file=../../.license-preamble
//

// Package buildenv_testutils is a generated GoMock package.
package buildenv_testutils

import (
	reflect "reflect"

	buildenv "github.com/microsoft/azure-linux-dev-tools/internal/buildenv"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// CreateEnv mocks base method.
func (m *MockFactory) CreateEnv(options buildenv.CreateOptions) (buildenv.BuildEnv, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEnv", options)
	ret0, _ := ret[0].(buildenv.BuildEnv)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEnv indicates an expected call of CreateEnv.
func (mr *MockFactoryMockRecorder) CreateEnv(options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEnv", reflect.TypeOf((*MockFactory)(nil).CreateEnv), options)
}

// MockRPMAwareFactory is a mock of RPMAwareFactory interface.
type MockRPMAwareFactory struct {
	ctrl     *gomock.Controller
	recorder *MockRPMAwareFactoryMockRecorder
	isgomock struct{}
}

// MockRPMAwareFactoryMockRecorder is the mock recorder for MockRPMAwareFactory.
type MockRPMAwareFactoryMockRecorder struct {
	mock *MockRPMAwareFactory
}

// NewMockRPMAwareFactory creates a new mock instance.
func NewMockRPMAwareFactory(ctrl *gomock.Controller) *MockRPMAwareFactory {
	mock := &MockRPMAwareFactory{ctrl: ctrl}
	mock.recorder = &MockRPMAwareFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPMAwareFactory) EXPECT() *MockRPMAwareFactoryMockRecorder {
	return m.recorder
}

// CreateRPMAwareEnv mocks base method.
func (m *MockRPMAwareFactory) CreateRPMAwareEnv(options buildenv.CreateOptions) (buildenv.RPMAwareBuildEnv, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRPMAwareEnv", options)
	ret0, _ := ret[0].(buildenv.RPMAwareBuildEnv)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRPMAwareEnv indicates an expected call of CreateRPMAwareEnv.
func (mr *MockRPMAwareFactoryMockRecorder) CreateRPMAwareEnv(options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRPMAwareEnv", reflect.TypeOf((*MockRPMAwareFactory)(nil).CreateRPMAwareEnv), options)
}
