// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: extractor.go
//
// Generated by this command:
//
//	mockgen -source=extractor.go -destination=rpm_test/extractor_mocks.go -package=rpm_test --copyright_file=../../.license-preamble
//

// Package rpm_test is a generated GoMock package.
package rpm_test

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRPMExtractor is a mock of RPMExtractor interface.
type MockRPMExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockRPMExtractorMockRecorder
	isgomock struct{}
}

// MockRPMExtractorMockRecorder is the mock recorder for MockRPMExtractor.
type MockRPMExtractorMockRecorder struct {
	mock *MockRPMExtractor
}

// NewMockRPMExtractor creates a new mock instance.
func NewMockRPMExtractor(ctrl *gomock.Controller) *MockRPMExtractor {
	mock := &MockRPMExtractor{ctrl: ctrl}
	mock.recorder = &MockRPMExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPMExtractor) EXPECT() *MockRPMExtractorMockRecorder {
	return m.recorder
}

// Extract mocks base method.
func (m *MockRPMExtractor) Extract(rpmStream io.Reader, destDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", rpmStream, destDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Extract indicates an expected call of Extract.
func (mr *MockRPMExtractorMockRecorder) Extract(rpmStream, destDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockRPMExtractor)(nil).Extract), rpmStream, destDir)
}
