// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: repoquery.go
//
// Generated by this command:
//
//	mockgen -source=repoquery.go -destination=rpm_test/repoquery_mocks.go -package=rpm_test --copyright_file=../../.license-preamble
//

// Package rpm_test is a generated GoMock package.
package rpm_test

import (
	context "context"
	reflect "reflect"

	rpm "github.com/microsoft/azure-linux-dev-tools/internal/rpm"
	gomock "go.uber.org/mock/gomock"
)

// MockRepoQuerier is a mock of RepoQuerier interface.
type MockRepoQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockRepoQuerierMockRecorder
	isgomock struct{}
}

// MockRepoQuerierMockRecorder is the mock recorder for MockRepoQuerier.
type MockRepoQuerierMockRecorder struct {
	mock *MockRepoQuerier
}

// NewMockRepoQuerier creates a new mock instance.
func NewMockRepoQuerier(ctrl *gomock.Controller) *MockRepoQuerier {
	mock := &MockRepoQuerier{ctrl: ctrl}
	mock.recorder = &MockRepoQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoQuerier) EXPECT() *MockRepoQuerierMockRecorder {
	return m.recorder
}

// GetLatestVersion mocks base method.
func (m *MockRepoQuerier) GetLatestVersion(ctx context.Context, packageName string) (*rpm.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVersion", ctx, packageName)
	ret0, _ := ret[0].(*rpm.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestVersion indicates an expected call of GetLatestVersion.
func (mr *MockRepoQuerierMockRecorder) GetLatestVersion(ctx, packageName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVersion", reflect.TypeOf((*MockRepoQuerier)(nil).GetLatestVersion), ctx, packageName)
}

// GetRPMLocation mocks base method.
func (m *MockRepoQuerier) GetRPMLocation(ctx context.Context, packageName string, version *rpm.Version) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRPMLocation", ctx, packageName, version)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRPMLocation indicates an expected call of GetRPMLocation.
func (mr *MockRepoQuerierMockRecorder) GetRPMLocation(ctx, packageName, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRPMLocation", reflect.TypeOf((*MockRepoQuerier)(nil).GetRPMLocation), ctx, packageName, version)
}
