// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=opctx_test/opctx_mocks.go -package=opctx_test --copyright_file=../../../.license-preamble
//

// Package opctx_test is a generated GoMock package.
package opctx_test

import (
	context "context"
	io "io"
	os "os"
	exec "os/exec"
	reflect "reflect"
	time "time"

	opctx "github.com/microsoft/azure-linux-dev-tools/internal/global/opctx"
	afero "github.com/spf13/afero"
	gomock "go.uber.org/mock/gomock"
)

// MockCtx is a mock of Ctx interface.
type MockCtx struct {
	ctrl     *gomock.Controller
	recorder *MockCtxMockRecorder
	isgomock struct{}
}

// MockCtxMockRecorder is the mock recorder for MockCtx.
type MockCtxMockRecorder struct {
	mock *MockCtx
}

// NewMockCtx creates a new mock instance.
func NewMockCtx(ctrl *gomock.Controller) *MockCtx {
	mock := &MockCtx{ctrl: ctrl}
	mock.recorder = &MockCtxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCtx) EXPECT() *MockCtxMockRecorder {
	return m.recorder
}

// AllPromptsAccepted mocks base method.
func (m *MockCtx) AllPromptsAccepted() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllPromptsAccepted")
	ret0, _ := ret[0].(bool)
	return ret0
}

// AllPromptsAccepted indicates an expected call of AllPromptsAccepted.
func (mr *MockCtxMockRecorder) AllPromptsAccepted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllPromptsAccepted", reflect.TypeOf((*MockCtx)(nil).AllPromptsAccepted))
}

// Command mocks base method.
func (m *MockCtx) Command(cmd *exec.Cmd) (opctx.Cmd, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Command", cmd)
	ret0, _ := ret[0].(opctx.Cmd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Command indicates an expected call of Command.
func (mr *MockCtxMockRecorder) Command(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Command", reflect.TypeOf((*MockCtx)(nil).Command), cmd)
}

// CommandInSearchPath mocks base method.
func (m *MockCtx) CommandInSearchPath(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommandInSearchPath", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CommandInSearchPath indicates an expected call of CommandInSearchPath.
func (mr *MockCtxMockRecorder) CommandInSearchPath(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommandInSearchPath", reflect.TypeOf((*MockCtx)(nil).CommandInSearchPath), name)
}

// ConfirmAutoResolution mocks base method.
func (m *MockCtx) ConfirmAutoResolution(text string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmAutoResolution", text)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ConfirmAutoResolution indicates an expected call of ConfirmAutoResolution.
func (mr *MockCtxMockRecorder) ConfirmAutoResolution(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmAutoResolution", reflect.TypeOf((*MockCtx)(nil).ConfirmAutoResolution), text)
}

// Deadline mocks base method.
func (m *MockCtx) Deadline() (time.Time, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deadline")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Deadline indicates an expected call of Deadline.
func (mr *MockCtxMockRecorder) Deadline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deadline", reflect.TypeOf((*MockCtx)(nil).Deadline))
}

// Done mocks base method.
func (m *MockCtx) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockCtxMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockCtx)(nil).Done))
}

// DryRun mocks base method.
func (m *MockCtx) DryRun() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DryRun")
	ret0, _ := ret[0].(bool)
	return ret0
}

// DryRun indicates an expected call of DryRun.
func (mr *MockCtxMockRecorder) DryRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DryRun", reflect.TypeOf((*MockCtx)(nil).DryRun))
}

// Err mocks base method.
func (m *MockCtx) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockCtxMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockCtx)(nil).Err))
}

// Event mocks base method.
func (m *MockCtx) Event(name string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Event", varargs...)
}

// Event indicates an expected call of Event.
func (mr *MockCtxMockRecorder) Event(name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Event", reflect.TypeOf((*MockCtx)(nil).Event), varargs...)
}

// FS mocks base method.
func (m *MockCtx) FS() opctx.FS {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FS")
	ret0, _ := ret[0].(opctx.FS)
	return ret0
}

// FS indicates an expected call of FS.
func (mr *MockCtxMockRecorder) FS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FS", reflect.TypeOf((*MockCtx)(nil).FS))
}

// OSEnv mocks base method.
func (m *MockCtx) OSEnv() opctx.OSEnv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OSEnv")
	ret0, _ := ret[0].(opctx.OSEnv)
	return ret0
}

// OSEnv indicates an expected call of OSEnv.
func (mr *MockCtxMockRecorder) OSEnv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OSEnv", reflect.TypeOf((*MockCtx)(nil).OSEnv))
}

// PromptsAllowed mocks base method.
func (m *MockCtx) PromptsAllowed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptsAllowed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// PromptsAllowed indicates an expected call of PromptsAllowed.
func (mr *MockCtxMockRecorder) PromptsAllowed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptsAllowed", reflect.TypeOf((*MockCtx)(nil).PromptsAllowed))
}

// StartEvent mocks base method.
func (m *MockCtx) StartEvent(name string, args ...any) opctx.Event {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartEvent", varargs...)
	ret0, _ := ret[0].(opctx.Event)
	return ret0
}

// StartEvent indicates an expected call of StartEvent.
func (mr *MockCtxMockRecorder) StartEvent(name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartEvent", reflect.TypeOf((*MockCtx)(nil).StartEvent), varargs...)
}

// Value mocks base method.
func (m *MockCtx) Value(key any) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value", key)
	ret0, _ := ret[0].(any)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockCtxMockRecorder) Value(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockCtx)(nil).Value), key)
}

// Verbose mocks base method.
func (m *MockCtx) Verbose() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verbose")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Verbose indicates an expected call of Verbose.
func (mr *MockCtxMockRecorder) Verbose() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verbose", reflect.TypeOf((*MockCtx)(nil).Verbose))
}

// MockDryRunnable is a mock of DryRunnable interface.
type MockDryRunnable struct {
	ctrl     *gomock.Controller
	recorder *MockDryRunnableMockRecorder
	isgomock struct{}
}

// MockDryRunnableMockRecorder is the mock recorder for MockDryRunnable.
type MockDryRunnableMockRecorder struct {
	mock *MockDryRunnable
}

// NewMockDryRunnable creates a new mock instance.
func NewMockDryRunnable(ctrl *gomock.Controller) *MockDryRunnable {
	mock := &MockDryRunnable{ctrl: ctrl}
	mock.recorder = &MockDryRunnableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDryRunnable) EXPECT() *MockDryRunnableMockRecorder {
	return m.recorder
}

// DryRun mocks base method.
func (m *MockDryRunnable) DryRun() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DryRun")
	ret0, _ := ret[0].(bool)
	return ret0
}

// DryRun indicates an expected call of DryRun.
func (mr *MockDryRunnableMockRecorder) DryRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DryRun", reflect.TypeOf((*MockDryRunnable)(nil).DryRun))
}

// MockEvent is a mock of Event interface.
type MockEvent struct {
	ctrl     *gomock.Controller
	recorder *MockEventMockRecorder
	isgomock struct{}
}

// MockEventMockRecorder is the mock recorder for MockEvent.
type MockEventMockRecorder struct {
	mock *MockEvent
}

// NewMockEvent creates a new mock instance.
func NewMockEvent(ctrl *gomock.Controller) *MockEvent {
	mock := &MockEvent{ctrl: ctrl}
	mock.recorder = &MockEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvent) EXPECT() *MockEventMockRecorder {
	return m.recorder
}

// End mocks base method.
func (m *MockEvent) End() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "End")
}

// End indicates an expected call of End.
func (mr *MockEventMockRecorder) End() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "End", reflect.TypeOf((*MockEvent)(nil).End))
}

// SetLongRunning mocks base method.
func (m *MockEvent) SetLongRunning(title string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLongRunning", title)
}

// SetLongRunning indicates an expected call of SetLongRunning.
func (mr *MockEventMockRecorder) SetLongRunning(title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLongRunning", reflect.TypeOf((*MockEvent)(nil).SetLongRunning), title)
}

// SetProgress mocks base method.
func (m *MockEvent) SetProgress(unitsComplete, totalUnits int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProgress", unitsComplete, totalUnits)
}

// SetProgress indicates an expected call of SetProgress.
func (mr *MockEventMockRecorder) SetProgress(unitsComplete, totalUnits any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProgress", reflect.TypeOf((*MockEvent)(nil).SetProgress), unitsComplete, totalUnits)
}

// MockEventListener is a mock of EventListener interface.
type MockEventListener struct {
	ctrl     *gomock.Controller
	recorder *MockEventListenerMockRecorder
	isgomock struct{}
}

// MockEventListenerMockRecorder is the mock recorder for MockEventListener.
type MockEventListenerMockRecorder struct {
	mock *MockEventListener
}

// NewMockEventListener creates a new mock instance.
func NewMockEventListener(ctrl *gomock.Controller) *MockEventListener {
	mock := &MockEventListener{ctrl: ctrl}
	mock.recorder = &MockEventListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventListener) EXPECT() *MockEventListenerMockRecorder {
	return m.recorder
}

// Event mocks base method.
func (m *MockEventListener) Event(name string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Event", varargs...)
}

// Event indicates an expected call of Event.
func (mr *MockEventListenerMockRecorder) Event(name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Event", reflect.TypeOf((*MockEventListener)(nil).Event), varargs...)
}

// StartEvent mocks base method.
func (m *MockEventListener) StartEvent(name string, args ...any) opctx.Event {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartEvent", varargs...)
	ret0, _ := ret[0].(opctx.Event)
	return ret0
}

// StartEvent indicates an expected call of StartEvent.
func (mr *MockEventListenerMockRecorder) StartEvent(name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartEvent", reflect.TypeOf((*MockEventListener)(nil).StartEvent), varargs...)
}

// MockVerbosity is a mock of Verbosity interface.
type MockVerbosity struct {
	ctrl     *gomock.Controller
	recorder *MockVerbosityMockRecorder
	isgomock struct{}
}

// MockVerbosityMockRecorder is the mock recorder for MockVerbosity.
type MockVerbosityMockRecorder struct {
	mock *MockVerbosity
}

// NewMockVerbosity creates a new mock instance.
func NewMockVerbosity(ctrl *gomock.Controller) *MockVerbosity {
	mock := &MockVerbosity{ctrl: ctrl}
	mock.recorder = &MockVerbosityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerbosity) EXPECT() *MockVerbosityMockRecorder {
	return m.recorder
}

// Verbose mocks base method.
func (m *MockVerbosity) Verbose() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verbose")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Verbose indicates an expected call of Verbose.
func (mr *MockVerbosityMockRecorder) Verbose() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verbose", reflect.TypeOf((*MockVerbosity)(nil).Verbose))
}

// MockPrompter is a mock of Prompter interface.
type MockPrompter struct {
	ctrl     *gomock.Controller
	recorder *MockPrompterMockRecorder
	isgomock struct{}
}

// MockPrompterMockRecorder is the mock recorder for MockPrompter.
type MockPrompterMockRecorder struct {
	mock *MockPrompter
}

// NewMockPrompter creates a new mock instance.
func NewMockPrompter(ctrl *gomock.Controller) *MockPrompter {
	mock := &MockPrompter{ctrl: ctrl}
	mock.recorder = &MockPrompterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrompter) EXPECT() *MockPrompterMockRecorder {
	return m.recorder
}

// AllPromptsAccepted mocks base method.
func (m *MockPrompter) AllPromptsAccepted() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllPromptsAccepted")
	ret0, _ := ret[0].(bool)
	return ret0
}

// AllPromptsAccepted indicates an expected call of AllPromptsAccepted.
func (mr *MockPrompterMockRecorder) AllPromptsAccepted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllPromptsAccepted", reflect.TypeOf((*MockPrompter)(nil).AllPromptsAccepted))
}

// ConfirmAutoResolution mocks base method.
func (m *MockPrompter) ConfirmAutoResolution(text string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmAutoResolution", text)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ConfirmAutoResolution indicates an expected call of ConfirmAutoResolution.
func (mr *MockPrompterMockRecorder) ConfirmAutoResolution(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmAutoResolution", reflect.TypeOf((*MockPrompter)(nil).ConfirmAutoResolution), text)
}

// PromptsAllowed mocks base method.
func (m *MockPrompter) PromptsAllowed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptsAllowed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// PromptsAllowed indicates an expected call of PromptsAllowed.
func (mr *MockPrompterMockRecorder) PromptsAllowed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptsAllowed", reflect.TypeOf((*MockPrompter)(nil).PromptsAllowed))
}

// MockCmdFactory is a mock of CmdFactory interface.
type MockCmdFactory struct {
	ctrl     *gomock.Controller
	recorder *MockCmdFactoryMockRecorder
	isgomock struct{}
}

// MockCmdFactoryMockRecorder is the mock recorder for MockCmdFactory.
type MockCmdFactoryMockRecorder struct {
	mock *MockCmdFactory
}

// NewMockCmdFactory creates a new mock instance.
func NewMockCmdFactory(ctrl *gomock.Controller) *MockCmdFactory {
	mock := &MockCmdFactory{ctrl: ctrl}
	mock.recorder = &MockCmdFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCmdFactory) EXPECT() *MockCmdFactoryMockRecorder {
	return m.recorder
}

// Command mocks base method.
func (m *MockCmdFactory) Command(cmd *exec.Cmd) (opctx.Cmd, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Command", cmd)
	ret0, _ := ret[0].(opctx.Cmd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Command indicates an expected call of Command.
func (mr *MockCmdFactoryMockRecorder) Command(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Command", reflect.TypeOf((*MockCmdFactory)(nil).Command), cmd)
}

// CommandInSearchPath mocks base method.
func (m *MockCmdFactory) CommandInSearchPath(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommandInSearchPath", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CommandInSearchPath indicates an expected call of CommandInSearchPath.
func (mr *MockCmdFactoryMockRecorder) CommandInSearchPath(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommandInSearchPath", reflect.TypeOf((*MockCmdFactory)(nil).CommandInSearchPath), name)
}

// MockFileSystemFactory is a mock of FileSystemFactory interface.
type MockFileSystemFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFileSystemFactoryMockRecorder
	isgomock struct{}
}

// MockFileSystemFactoryMockRecorder is the mock recorder for MockFileSystemFactory.
type MockFileSystemFactoryMockRecorder struct {
	mock *MockFileSystemFactory
}

// NewMockFileSystemFactory creates a new mock instance.
func NewMockFileSystemFactory(ctrl *gomock.Controller) *MockFileSystemFactory {
	mock := &MockFileSystemFactory{ctrl: ctrl}
	mock.recorder = &MockFileSystemFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileSystemFactory) EXPECT() *MockFileSystemFactoryMockRecorder {
	return m.recorder
}

// FS mocks base method.
func (m *MockFileSystemFactory) FS() opctx.FS {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FS")
	ret0, _ := ret[0].(opctx.FS)
	return ret0
}

// FS indicates an expected call of FS.
func (mr *MockFileSystemFactoryMockRecorder) FS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FS", reflect.TypeOf((*MockFileSystemFactory)(nil).FS))
}

// MockOSEnvFactory is a mock of OSEnvFactory interface.
type MockOSEnvFactory struct {
	ctrl     *gomock.Controller
	recorder *MockOSEnvFactoryMockRecorder
	isgomock struct{}
}

// MockOSEnvFactoryMockRecorder is the mock recorder for MockOSEnvFactory.
type MockOSEnvFactoryMockRecorder struct {
	mock *MockOSEnvFactory
}

// NewMockOSEnvFactory creates a new mock instance.
func NewMockOSEnvFactory(ctrl *gomock.Controller) *MockOSEnvFactory {
	mock := &MockOSEnvFactory{ctrl: ctrl}
	mock.recorder = &MockOSEnvFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOSEnvFactory) EXPECT() *MockOSEnvFactoryMockRecorder {
	return m.recorder
}

// OSEnv mocks base method.
func (m *MockOSEnvFactory) OSEnv() opctx.OSEnv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OSEnv")
	ret0, _ := ret[0].(opctx.OSEnv)
	return ret0
}

// OSEnv indicates an expected call of OSEnv.
func (mr *MockOSEnvFactoryMockRecorder) OSEnv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OSEnv", reflect.TypeOf((*MockOSEnvFactory)(nil).OSEnv))
}

// MockFS is a mock of FS interface.
type MockFS struct {
	ctrl     *gomock.Controller
	recorder *MockFSMockRecorder
	isgomock struct{}
}

// MockFSMockRecorder is the mock recorder for MockFS.
type MockFSMockRecorder struct {
	mock *MockFS
}

// NewMockFS creates a new mock instance.
func NewMockFS(ctrl *gomock.Controller) *MockFS {
	mock := &MockFS{ctrl: ctrl}
	mock.recorder = &MockFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFS) EXPECT() *MockFSMockRecorder {
	return m.recorder
}

// Chmod mocks base method.
func (m *MockFS) Chmod(name string, mode os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chmod", name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chmod indicates an expected call of Chmod.
func (mr *MockFSMockRecorder) Chmod(name, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chmod", reflect.TypeOf((*MockFS)(nil).Chmod), name, mode)
}

// Chown mocks base method.
func (m *MockFS) Chown(name string, uid, gid int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chown", name, uid, gid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chown indicates an expected call of Chown.
func (mr *MockFSMockRecorder) Chown(name, uid, gid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chown", reflect.TypeOf((*MockFS)(nil).Chown), name, uid, gid)
}

// Chtimes mocks base method.
func (m *MockFS) Chtimes(name string, atime, mtime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chtimes", name, atime, mtime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chtimes indicates an expected call of Chtimes.
func (mr *MockFSMockRecorder) Chtimes(name, atime, mtime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chtimes", reflect.TypeOf((*MockFS)(nil).Chtimes), name, atime, mtime)
}

// Create mocks base method.
func (m *MockFS) Create(name string) (afero.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name)
	ret0, _ := ret[0].(afero.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFSMockRecorder) Create(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFS)(nil).Create), name)
}

// Mkdir mocks base method.
func (m *MockFS) Mkdir(name string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mkdir", name, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mkdir indicates an expected call of Mkdir.
func (mr *MockFSMockRecorder) Mkdir(name, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mkdir", reflect.TypeOf((*MockFS)(nil).Mkdir), name, perm)
}

// MkdirAll mocks base method.
func (m *MockFS) MkdirAll(path string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockFSMockRecorder) MkdirAll(path, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockFS)(nil).MkdirAll), path, perm)
}

// Name mocks base method.
func (m *MockFS) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockFSMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockFS)(nil).Name))
}

// Open mocks base method.
func (m *MockFS) Open(name string) (afero.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(afero.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockFS)(nil).Open), name)
}

// OpenFile mocks base method.
func (m *MockFS) OpenFile(name string, flag int, perm os.FileMode) (afero.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", name, flag, perm)
	ret0, _ := ret[0].(afero.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockFSMockRecorder) OpenFile(name, flag, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockFS)(nil).OpenFile), name, flag, perm)
}

// Remove mocks base method.
func (m *MockFS) Remove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFSMockRecorder) Remove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFS)(nil).Remove), name)
}

// RemoveAll mocks base method.
func (m *MockFS) RemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockFSMockRecorder) RemoveAll(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockFS)(nil).RemoveAll), path)
}

// Rename mocks base method.
func (m *MockFS) Rename(oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockFSMockRecorder) Rename(oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockFS)(nil).Rename), oldname, newname)
}

// Stat mocks base method.
func (m *MockFS) Stat(name string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", name)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockFSMockRecorder) Stat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockFS)(nil).Stat), name)
}

// MockFile is a mock of File interface.
type MockFile struct {
	ctrl     *gomock.Controller
	recorder *MockFileMockRecorder
	isgomock struct{}
}

// MockFileMockRecorder is the mock recorder for MockFile.
type MockFileMockRecorder struct {
	mock *MockFile
}

// NewMockFile creates a new mock instance.
func NewMockFile(ctrl *gomock.Controller) *MockFile {
	mock := &MockFile{ctrl: ctrl}
	mock.recorder = &MockFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFile) EXPECT() *MockFileMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockFile) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFileMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFile)(nil).Close))
}

// Name mocks base method.
func (m *MockFile) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockFileMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockFile)(nil).Name))
}

// Read mocks base method.
func (m *MockFile) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockFileMockRecorder) Read(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockFile)(nil).Read), p)
}

// ReadAt mocks base method.
func (m *MockFile) ReadAt(p []byte, off int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAt", p, off)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAt indicates an expected call of ReadAt.
func (mr *MockFileMockRecorder) ReadAt(p, off any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAt", reflect.TypeOf((*MockFile)(nil).ReadAt), p, off)
}

// Readdir mocks base method.
func (m *MockFile) Readdir(count int) ([]os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Readdir", count)
	ret0, _ := ret[0].([]os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Readdir indicates an expected call of Readdir.
func (mr *MockFileMockRecorder) Readdir(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Readdir", reflect.TypeOf((*MockFile)(nil).Readdir), count)
}

// Readdirnames mocks base method.
func (m *MockFile) Readdirnames(n int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Readdirnames", n)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Readdirnames indicates an expected call of Readdirnames.
func (mr *MockFileMockRecorder) Readdirnames(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Readdirnames", reflect.TypeOf((*MockFile)(nil).Readdirnames), n)
}

// Seek mocks base method.
func (m *MockFile) Seek(offset int64, whence int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", offset, whence)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seek indicates an expected call of Seek.
func (mr *MockFileMockRecorder) Seek(offset, whence any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*MockFile)(nil).Seek), offset, whence)
}

// Stat mocks base method.
func (m *MockFile) Stat() (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockFileMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockFile)(nil).Stat))
}

// Sync mocks base method.
func (m *MockFile) Sync() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync")
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockFileMockRecorder) Sync() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockFile)(nil).Sync))
}

// Truncate mocks base method.
func (m *MockFile) Truncate(size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Truncate", size)
	ret0, _ := ret[0].(error)
	return ret0
}

// Truncate indicates an expected call of Truncate.
func (mr *MockFileMockRecorder) Truncate(size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Truncate", reflect.TypeOf((*MockFile)(nil).Truncate), size)
}

// Write mocks base method.
func (m *MockFile) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockFileMockRecorder) Write(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockFile)(nil).Write), p)
}

// WriteAt mocks base method.
func (m *MockFile) WriteAt(p []byte, off int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAt", p, off)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteAt indicates an expected call of WriteAt.
func (mr *MockFileMockRecorder) WriteAt(p, off any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAt", reflect.TypeOf((*MockFile)(nil).WriteAt), p, off)
}

// WriteString mocks base method.
func (m *MockFile) WriteString(s string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteString", s)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteString indicates an expected call of WriteString.
func (mr *MockFileMockRecorder) WriteString(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteString", reflect.TypeOf((*MockFile)(nil).WriteString), s)
}

// MockCmd is a mock of Cmd interface.
type MockCmd struct {
	ctrl     *gomock.Controller
	recorder *MockCmdMockRecorder
	isgomock struct{}
}

// MockCmdMockRecorder is the mock recorder for MockCmd.
type MockCmdMockRecorder struct {
	mock *MockCmd
}

// NewMockCmd creates a new mock instance.
func NewMockCmd(ctrl *gomock.Controller) *MockCmd {
	mock := &MockCmd{ctrl: ctrl}
	mock.recorder = &MockCmdMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCmd) EXPECT() *MockCmdMockRecorder {
	return m.recorder
}

// AddRealTimeFileListener mocks base method.
func (m *MockCmd) AddRealTimeFileListener(path string, listener opctx.LineListener) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRealTimeFileListener", path, listener)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRealTimeFileListener indicates an expected call of AddRealTimeFileListener.
func (mr *MockCmdMockRecorder) AddRealTimeFileListener(path, listener any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRealTimeFileListener", reflect.TypeOf((*MockCmd)(nil).AddRealTimeFileListener), path, listener)
}

// GetArgs mocks base method.
func (m *MockCmd) GetArgs() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArgs")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetArgs indicates an expected call of GetArgs.
func (mr *MockCmdMockRecorder) GetArgs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArgs", reflect.TypeOf((*MockCmd)(nil).GetArgs))
}

// Run mocks base method.
func (m *MockCmd) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockCmdMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCmd)(nil).Run), ctx)
}

// RunAndGetOutput mocks base method.
func (m *MockCmd) RunAndGetOutput(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunAndGetOutput", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunAndGetOutput indicates an expected call of RunAndGetOutput.
func (mr *MockCmdMockRecorder) RunAndGetOutput(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAndGetOutput", reflect.TypeOf((*MockCmd)(nil).RunAndGetOutput), ctx)
}

// SetDescription mocks base method.
func (m *MockCmd) SetDescription(description string) opctx.Cmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDescription", description)
	ret0, _ := ret[0].(opctx.Cmd)
	return ret0
}

// SetDescription indicates an expected call of SetDescription.
func (mr *MockCmdMockRecorder) SetDescription(description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDescription", reflect.TypeOf((*MockCmd)(nil).SetDescription), description)
}

// SetLongRunning mocks base method.
func (m *MockCmd) SetLongRunning(progressTitle string) opctx.Cmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLongRunning", progressTitle)
	ret0, _ := ret[0].(opctx.Cmd)
	return ret0
}

// SetLongRunning indicates an expected call of SetLongRunning.
func (mr *MockCmdMockRecorder) SetLongRunning(progressTitle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLongRunning", reflect.TypeOf((*MockCmd)(nil).SetLongRunning), progressTitle)
}

// SetRealTimeStderrListener mocks base method.
func (m *MockCmd) SetRealTimeStderrListener(listener opctx.LineListener) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRealTimeStderrListener", listener)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRealTimeStderrListener indicates an expected call of SetRealTimeStderrListener.
func (mr *MockCmdMockRecorder) SetRealTimeStderrListener(listener any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRealTimeStderrListener", reflect.TypeOf((*MockCmd)(nil).SetRealTimeStderrListener), listener)
}

// SetRealTimeStdoutListener mocks base method.
func (m *MockCmd) SetRealTimeStdoutListener(listener opctx.LineListener) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRealTimeStdoutListener", listener)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRealTimeStdoutListener indicates an expected call of SetRealTimeStdoutListener.
func (mr *MockCmdMockRecorder) SetRealTimeStdoutListener(listener any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRealTimeStdoutListener", reflect.TypeOf((*MockCmd)(nil).SetRealTimeStdoutListener), listener)
}

// SetStderr mocks base method.
func (m *MockCmd) SetStderr(stderr io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStderr", stderr)
}

// SetStderr indicates an expected call of SetStderr.
func (mr *MockCmdMockRecorder) SetStderr(stderr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStderr", reflect.TypeOf((*MockCmd)(nil).SetStderr), stderr)
}

// SetStdin mocks base method.
func (m *MockCmd) SetStdin(stdin io.Reader) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStdin", stdin)
}

// SetStdin indicates an expected call of SetStdin.
func (mr *MockCmdMockRecorder) SetStdin(stdin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStdin", reflect.TypeOf((*MockCmd)(nil).SetStdin), stdin)
}

// SetStdout mocks base method.
func (m *MockCmd) SetStdout(stdout io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStdout", stdout)
}

// SetStdout indicates an expected call of SetStdout.
func (mr *MockCmdMockRecorder) SetStdout(stdout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStdout", reflect.TypeOf((*MockCmd)(nil).SetStdout), stdout)
}

// Start mocks base method.
func (m *MockCmd) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCmdMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCmd)(nil).Start), ctx)
}

// Wait mocks base method.
func (m *MockCmd) Wait(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockCmdMockRecorder) Wait(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockCmd)(nil).Wait), ctx)
}

// MockOSEnv is a mock of OSEnv interface.
type MockOSEnv struct {
	ctrl     *gomock.Controller
	recorder *MockOSEnvMockRecorder
	isgomock struct{}
}

// MockOSEnvMockRecorder is the mock recorder for MockOSEnv.
type MockOSEnvMockRecorder struct {
	mock *MockOSEnv
}

// NewMockOSEnv creates a new mock instance.
func NewMockOSEnv(ctrl *gomock.Controller) *MockOSEnv {
	mock := &MockOSEnv{ctrl: ctrl}
	mock.recorder = &MockOSEnvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOSEnv) EXPECT() *MockOSEnvMockRecorder {
	return m.recorder
}

// Chdir mocks base method.
func (m *MockOSEnv) Chdir(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chdir", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chdir indicates an expected call of Chdir.
func (mr *MockOSEnvMockRecorder) Chdir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chdir", reflect.TypeOf((*MockOSEnv)(nil).Chdir), path)
}

// Getenv mocks base method.
func (m *MockOSEnv) Getenv(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getenv", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// Getenv indicates an expected call of Getenv.
func (mr *MockOSEnvMockRecorder) Getenv(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getenv", reflect.TypeOf((*MockOSEnv)(nil).Getenv), key)
}

// Getwd mocks base method.
func (m *MockOSEnv) Getwd() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getwd")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Getwd indicates an expected call of Getwd.
func (mr *MockOSEnvMockRecorder) Getwd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getwd", reflect.TypeOf((*MockOSEnv)(nil).Getwd))
}

// IsCurrentUserMemberOf mocks base method.
func (m *MockOSEnv) IsCurrentUserMemberOf(groupName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCurrentUserMemberOf", groupName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCurrentUserMemberOf indicates an expected call of IsCurrentUserMemberOf.
func (mr *MockOSEnvMockRecorder) IsCurrentUserMemberOf(groupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCurrentUserMemberOf", reflect.TypeOf((*MockOSEnv)(nil).IsCurrentUserMemberOf), groupName)
}

// LookupGroupID mocks base method.
func (m *MockOSEnv) LookupGroupID(groupName string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupGroupID", groupName)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupGroupID indicates an expected call of LookupGroupID.
func (mr *MockOSEnvMockRecorder) LookupGroupID(groupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupGroupID", reflect.TypeOf((*MockOSEnv)(nil).LookupGroupID), groupName)
}
