// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: componentbuilder.go
//
// Generated by this command:
//
//	mockgen -source=componentbuilder.go -destination=componentbuilder_test/componentbuilder_mocks.go -package=componentbuilder --copyright_file=../../../../../.license-preamble
//

// Package componentbuilder is a generated GoMock package.
package componentbuilder

import (
	context "context"
	reflect "reflect"

	components "github.com/microsoft/azure-linux-dev-tools/internal/app/azldev/core/components"
	gomock "go.uber.org/mock/gomock"
)

// MockComponentBuilder is a mock of ComponentBuilder interface.
type MockComponentBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockComponentBuilderMockRecorder
	isgomock struct{}
}

// MockComponentBuilderMockRecorder is the mock recorder for MockComponentBuilder.
type MockComponentBuilderMockRecorder struct {
	mock *MockComponentBuilder
}

// NewMockComponentBuilder creates a new mock instance.
func NewMockComponentBuilder(ctrl *gomock.Controller) *MockComponentBuilder {
	mock := &MockComponentBuilder{ctrl: ctrl}
	mock.recorder = &MockComponentBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponentBuilder) EXPECT() *MockComponentBuilderMockRecorder {
	return m.recorder
}

// BuildBinaryPackage mocks base method.
func (m *MockComponentBuilder) BuildBinaryPackage(ctx context.Context, component components.Component, sourcePackagePath string, localRepoPaths []string, outputDir string, noCheck bool) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildBinaryPackage", ctx, component, sourcePackagePath, localRepoPaths, outputDir, noCheck)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildBinaryPackage indicates an expected call of BuildBinaryPackage.
func (mr *MockComponentBuilderMockRecorder) BuildBinaryPackage(ctx, component, sourcePackagePath, localRepoPaths, outputDir, noCheck any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildBinaryPackage", reflect.TypeOf((*MockComponentBuilder)(nil).BuildBinaryPackage), ctx, component, sourcePackagePath, localRepoPaths, outputDir, noCheck)
}

// BuildSourcePackage mocks base method.
func (m *MockComponentBuilder) BuildSourcePackage(ctx context.Context, component components.Component, localRepoPaths []string, outputDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildSourcePackage", ctx, component, localRepoPaths, outputDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildSourcePackage indicates an expected call of BuildSourcePackage.
func (mr *MockComponentBuilderMockRecorder) BuildSourcePackage(ctx, component, localRepoPaths, outputDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildSourcePackage", reflect.TypeOf((*MockComponentBuilder)(nil).BuildSourcePackage), ctx, component, localRepoPaths, outputDir)
}
