// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: fedorasource.go
//
// Generated by this command:
//
//	mockgen -source=fedorasource.go -destination=fedorasource_test/fedorasource_mocks.go -package=fedorasource_test --copyright_file=../../../../.license-preamble
//

// Package fedorasource_test is a generated GoMock package.
package fedorasource_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFedoraSourceDownloader is a mock of FedoraSourceDownloader interface.
type MockFedoraSourceDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockFedoraSourceDownloaderMockRecorder
	isgomock struct{}
}

// MockFedoraSourceDownloaderMockRecorder is the mock recorder for MockFedoraSourceDownloader.
type MockFedoraSourceDownloaderMockRecorder struct {
	mock *MockFedoraSourceDownloader
}

// NewMockFedoraSourceDownloader creates a new mock instance.
func NewMockFedoraSourceDownloader(ctrl *gomock.Controller) *MockFedoraSourceDownloader {
	mock := &MockFedoraSourceDownloader{ctrl: ctrl}
	mock.recorder = &MockFedoraSourceDownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFedoraSourceDownloader) EXPECT() *MockFedoraSourceDownloaderMockRecorder {
	return m.recorder
}

// ExtractSourcesFromRepo mocks base method.
func (m *MockFedoraSourceDownloader) ExtractSourcesFromRepo(ctx context.Context, repoDir, packageName, lookasideBaseURI string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractSourcesFromRepo", ctx, repoDir, packageName, lookasideBaseURI)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtractSourcesFromRepo indicates an expected call of ExtractSourcesFromRepo.
func (mr *MockFedoraSourceDownloaderMockRecorder) ExtractSourcesFromRepo(ctx, repoDir, packageName, lookasideBaseURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractSourcesFromRepo", reflect.TypeOf((*MockFedoraSourceDownloader)(nil).ExtractSourcesFromRepo), ctx, repoDir, packageName, lookasideBaseURI)
}
