// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: tablewriter.go
//
// Generated by this command:
//
//	mockgen -source=tablewriter.go -destination=reflectable_testutils/tablewriter_mocks.go -package=reflectable_testutils --copyright_file=../../../.license-preamble
//

// Package reflectable_testutils is a generated GoMock package.
package reflectable_testutils

import (
	reflect "reflect"

	reflectable "github.com/microsoft/azure-linux-dev-tools/internal/utils/reflectable"
	gomock "go.uber.org/mock/gomock"
)

// MockTableWriter is a mock of TableWriter interface.
type MockTableWriter struct {
	ctrl     *gomock.Controller
	recorder *MockTableWriterMockRecorder
	isgomock struct{}
}

// MockTableWriterMockRecorder is the mock recorder for MockTableWriter.
type MockTableWriterMockRecorder struct {
	mock *MockTableWriter
}

// NewMockTableWriter creates a new mock instance.
func NewMockTableWriter(ctrl *gomock.Controller) *MockTableWriter {
	mock := &MockTableWriter{ctrl: ctrl}
	mock.recorder = &MockTableWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableWriter) EXPECT() *MockTableWriterMockRecorder {
	return m.recorder
}

// EndColumn mocks base method.
func (m *MockTableWriter) EndColumn() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EndColumn")
}

// EndColumn indicates an expected call of EndColumn.
func (mr *MockTableWriterMockRecorder) EndColumn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndColumn", reflect.TypeOf((*MockTableWriter)(nil).EndColumn))
}

// EndHeaderRow mocks base method.
func (m *MockTableWriter) EndHeaderRow() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EndHeaderRow")
}

// EndHeaderRow indicates an expected call of EndHeaderRow.
func (mr *MockTableWriterMockRecorder) EndHeaderRow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndHeaderRow", reflect.TypeOf((*MockTableWriter)(nil).EndHeaderRow))
}

// EndRow mocks base method.
func (m *MockTableWriter) EndRow() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EndRow")
}

// EndRow indicates an expected call of EndRow.
func (mr *MockTableWriterMockRecorder) EndRow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndRow", reflect.TypeOf((*MockTableWriter)(nil).EndRow))
}

// EndTable mocks base method.
func (m *MockTableWriter) EndTable() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EndTable")
}

// EndTable indicates an expected call of EndTable.
func (mr *MockTableWriterMockRecorder) EndTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndTable", reflect.TypeOf((*MockTableWriter)(nil).EndTable))
}

// InTable mocks base method.
func (m *MockTableWriter) InTable() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTable")
	ret0, _ := ret[0].(bool)
	return ret0
}

// InTable indicates an expected call of InTable.
func (mr *MockTableWriterMockRecorder) InTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTable", reflect.TypeOf((*MockTableWriter)(nil).InTable))
}

// RightAlignColumn mocks base method.
func (m *MockTableWriter) RightAlignColumn(index int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RightAlignColumn", index)
}

// RightAlignColumn indicates an expected call of RightAlignColumn.
func (mr *MockTableWriterMockRecorder) RightAlignColumn(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RightAlignColumn", reflect.TypeOf((*MockTableWriter)(nil).RightAlignColumn), index)
}

// SortByColumn mocks base method.
func (m *MockTableWriter) SortByColumn(index int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SortByColumn", index)
}

// SortByColumn indicates an expected call of SortByColumn.
func (mr *MockTableWriterMockRecorder) SortByColumn(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SortByColumn", reflect.TypeOf((*MockTableWriter)(nil).SortByColumn), index)
}

// StartColumn mocks base method.
func (m *MockTableWriter) StartColumn() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartColumn")
}

// StartColumn indicates an expected call of StartColumn.
func (mr *MockTableWriterMockRecorder) StartColumn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartColumn", reflect.TypeOf((*MockTableWriter)(nil).StartColumn))
}

// StartHeaderRow mocks base method.
func (m *MockTableWriter) StartHeaderRow() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartHeaderRow")
}

// StartHeaderRow indicates an expected call of StartHeaderRow.
func (mr *MockTableWriterMockRecorder) StartHeaderRow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartHeaderRow", reflect.TypeOf((*MockTableWriter)(nil).StartHeaderRow))
}

// StartRow mocks base method.
func (m *MockTableWriter) StartRow() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartRow")
}

// StartRow indicates an expected call of StartRow.
func (mr *MockTableWriterMockRecorder) StartRow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRow", reflect.TypeOf((*MockTableWriter)(nil).StartRow))
}

// StartTable mocks base method.
func (m *MockTableWriter) StartTable(properties reflectable.TableProperties) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartTable", properties)
}

// StartTable indicates an expected call of StartTable.
func (mr *MockTableWriterMockRecorder) StartTable(properties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTable", reflect.TypeOf((*MockTableWriter)(nil).StartTable), properties)
}

// WriteValue mocks base method.
func (m *MockTableWriter) WriteValue(value any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteValue", value)
}

// WriteValue indicates an expected call of WriteValue.
func (mr *MockTableWriterMockRecorder) WriteValue(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteValue", reflect.TypeOf((*MockTableWriter)(nil).WriteValue), value)
}
