name: "Ensure generated code is up-to-date"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Run every night at 3:15am PST (11:15am UTC)
    - cron: "15 11 * * *"

# Cancel in-progress runs of this workflow if a new run is triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number ||
    github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-generated-code:
    name: Check generated code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Get go tools
        uses: ./.github/getgotools

      - name: Run code generation
        run: |
          mage -v generate

      - name: Run docs generation
        run: |
          mage -v docs

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git diff
            echo "::error::Generated code is not up to date - see changes above. Please run 'mage generate' and 'mage docs' locally and commit the changes."
            exit 1
          else
            echo "Generated code is up to date."
          fi
