name: "Check license compatibility"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Run every night at 3:15am PST (11:15am UTC)
    - cron: '15 11 * * *'

# Cancel in-progress runs of this workflow if a new run is triggered.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  license:
    name: "License check"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Get go tools
        uses: ./.github/getgotools
      - name: Run license checks
        run: |
          mage -v check licenses
      - name: Print license summary
        run: |
          cat out/licenses.csv
